environments:
    production:
        adapter: mysql
        host: localhost
        name:
        user:
        pass:
        port: 3306

    development:
        adapter: mysql
        host: localhost
        name:
        user:
        pass:
        port: 3306

    testing:
        adapter: mysql
        host: localhost
        name:
        user:
        pass:
        port: 3306